### ISSUE TITLE
Failing integrations tests build on nyxx_commander

### ISSUE THREAD

**Issue by l7ssha** [nyxx-discord/nyxx#157]
**Describe the bug**
Failing integrations tests build on `dev` branch on `nyxx_commander` step

**Additional context**
https://github.com/l7ssha/nyxx/runs/3161896412?check_suite_focus=true

```
[2021-07-26 13:21:51.097344] [INFO] [Client] Starting bot with pid: 1703. To stop the bot gracefully send SIGTERM or SIGKILL
[2021-07-26 13:21:51.098144] [INFO] [Commander] Commander ready!
[2021-07-26 13:21:51.166664] [INFO] [Client] Remaining 998 connections starts. Limit will reset at 2021-07-27 13:21:01.680645
[2021-07-26 13:21:51.238852] [INFO] [Shard Manager] Shard 0 connected to gateway!
[2021-07-26 13:21:52.396788] [SEVERE] [Shard Manager] Invalid session on shard 0. Reconnecting...
[2021-07-26 13:21:52.396823] [INFO] [Shard Manager] Connecting to gateway on shard 0!
Unhandled exception:
type 'Null' is not a subtype of type 'int' in type cast
#0      Shard._handleError (package:nyxx/src/internal/shard/Shard.dart:138)
#1      Shard._handle (package:nyxx/src/internal/shard/Shard.dart:192)
#2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1546)
#3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#5      _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:378)
#6      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244)
#7      _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:475)
#8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1546)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#11     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733)
#12     _StreamController._add (dart:async/stream_controller.dart:607)
#13     _StreamController.add (dart:async/stream_controller.dart:554)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
Error: Process completed with exit code 255.
```

**Comment by l7ssha** [comment]
Seems like problem resolved itself: https://github.com/nyxx-discord/nyxx/actions/runs/1071892594
