### ISSUE TITLE
Bot giving error when exiting using Ctrl C

### ISSUE THREAD

**Issue by vanxh** [nyxx-discord/nyxx#255]
```dart
import 'package:nyxx/nyxx.dart';
import '../config.dart';

class Client {
  /// Configuration for the client
  late final Config _config = Config();

  /// The nyxx client
  late INyxxWebsocket _bot;

  Client() {
    _bot = NyxxFactory.createNyxxWebsocket(
      _config.token,
      GatewayIntents.allUnprivileged,
    )
      ..registerPlugin(Logging())
      // ..registerPlugin(CliIntegration())
      ..registerPlugin(IgnoreExceptions());
  }

  /// Start the client.
  /// This will connect to the bot to discord
  Future<void> start() async {
    await _bot.connect();
    print(_bot);
  }
}
```
this is my client when i exit using ctrl c 
it gives this error:
```
[2021-12-21 15:28:38.815373] [SHOUT] [Client] Got Error: Message: [type 'Null' is not a subtype of type 'int' in type cast]. Stacktrace: 
#0      Shard._handleError (package:nyxx/src/internal/shard/shard.dart:229:41)
#1      Shard._handle (package:nyxx/src/internal/shard/shard.dart:283:7)
#2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1620:10)
#3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#5      _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:378:25)
#6      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#7      _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:475:11)
#8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1620:10)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#11     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#12     _StreamController._add (dart:async/stream_controller.dart:607:7)
#13     _StreamController.add (dart:async/stream_controller.dart:554:5)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)```

**Comment by abitofevrything** [comment]
Use .length instead of .cacheSize, cacheSize is the maximum size of the cache. -1 means unlimited size.
