### ISSUE TITLE
bug: Error whenever a post is reopened

### ISSUE THREAD

**Issue by phorcys420** [nyxx-discord/nyxx#515]
**Describe the bug**
Whenever a forum post is reopened, an error is thrown.

**To Reproduce**
1. Create a forum thread
2. Close the forum thread
3. Open the forum thread

**Desktop (please complete the following information):**
 - OS: Linux
 - Dart version: 3.0.1
 - Nyxx version: 5.1.0

**Additional context**
Stack trace
```
Error: InvalidSnowflakeException: Cannot parse [null] to Snowflake
Stack trace:
#0      new Snowflake (package:nyxx/src/core/snowflake.dart:39:9)
#1      new ThreadMemberUpdateEvent (package:nyxx/src/events/thread_members_update_event.dart:83:30)
#2      Shard.dispatch (package:nyxx/src/internal/shard/shard.dart:674:60)
#3      Shard.handlePayload (package:nyxx/src/internal/shard/shard.dart:327:9)
#4      Shard.handle (package:nyxx/src/internal/shard/shard.dart:239:16)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#6      CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
#11     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#12     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:474:11)
#13     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#16     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#17     _StreamController._add (dart:async/stream_controller.dart:650:7)
#18     _StreamController.add (dart:async/stream_controller.dart:598:5)
#19     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

**Comment by l7ssha** [comment]
Fixed in 5.1.1
